
$project_name = "PracticeCICD.xcodeproj"

default_platform(:ios)

platform :ios do
  lane :create_branch do

    increment_version_number(bump_type: "minor")

    # リリースブランチの作成とプッシュ
    new_version = get_version_number(xcodeproj: $project_name)
    branch_name = "release/ver#{new_version}"
    sh("echo #{new_version}")
    sh("git checkout -b #{branch_name}")
    sh("git add .")
    sh("git commit -m '#{new_version}に更新'")
    sh("git push --set-upstream origin #{branch_name}")
  end
end
