name: Create Pull Requests

on:
  push:
    branches:
      - 'release/*'

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Git config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge release branch into develop
          title: Merge release branch into develop
          branch: ${{ github.head_ref }}
          base: develop
          body: |
            Automatically created by GitHub Actions.

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge release branch into main
          title: Merge release branch into main
          branch: ${{ github.head_ref }}
          base: main
          body: |
            Automatically created by GitHub Actions.
