name: Create Pull Requests

on:
  push:
    branches:
      - 'release/**'

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create pull request to develop
      uses: actions/github-script@v6
      with:
        script: |
          const github = require('@actions/github');
          const context = github.context;

          const result = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Merge ${context.ref} into develop`,
            head: context.ref,
            base: 'develop',
            body: `This PR merges changes from ${context.ref} into develop.`,
          });

          console.log(result.data.html_url);

    - name: Create pull request to main
      uses: actions/github-script@v6
      with:
        script: |
          const github = require('@actions/github');
          const context = github.context;

          const result = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Merge ${context.ref} into main`,
            head: context.ref,
            base: 'main',
            body: `This PR merges changes from ${context.ref} into main.`,
          });

          console.log(result.data.html_url);
