name: Create Pull Requests

on:
  push:
    branches:
      - 'release/**'

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create pull request to develop
      run: gh pr create --base develop --head ${{ github.ref }} --title "Merge ${{ github.ref }} into develop" --body "This PR merges changes from ${{ github.ref }} into develop."

    - name: Create pull request to main
      run: gh pr create --base main --head ${{ github.ref }} --title "Merge ${{ github.ref }} into main" --body "This PR merges changes from ${{ github.ref }} into main."
